<DashboardScreen>:
    name: "dashboard"
    BoxLayout:
        orientation: "vertical"
        padding: 30
        spacing: 15

        Label:
            text: "Welcome to AI Attendance System"
            font_size: 26

        Label:
            id: time_label
            text: "Loading time..."
            font_size: 20

        Button:
            text: "Sign Out"
            on_release:
                app.root.current = "login"